# Generated by Django 6.0.5 on 2026-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('developer', 'Developer'), ('client', 'Client'), ('viewer', 'Viewer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
